<a href="https://colab.research.google.com/github/KristinaKryazheva/PDA-SOL/blob/main/%D1%81%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [2]:
import numpy as np
print(np.__version__)

1.23.5


2) Создать нулевой вектор размера 10

In [ ]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [ ]:
print(np.full(7,7))

[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
print(np.arange(10,101,2))

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
array=np.random.random(20)
print(array)
print(np.flip(array))

[0.96990479 0.36776207 0.36486089 0.34107437 0.50755679 0.28724371
 0.34032862 0.65546091 0.9702305  0.7030385  0.48350319 0.49440815
 0.54867431 0.73814631 0.45985946 0.86547691 0.99472757 0.02118703
 0.96389481 0.07133888]
[0.07133888 0.96389481 0.02118703 0.99472757 0.86547691 0.45985946
 0.73814631 0.54867431 0.49440815 0.48350319 0.7030385  0.9702305
 0.65546091 0.34032862 0.28724371 0.50755679 0.34107437 0.36486089
 0.36776207 0.96990479]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
print(np.arange(9).reshape((3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
print(np.eye(4,k=1))

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
matrix=np.diag([1,2,3,4])
matrix[matrix == 0] = 7
print(matrix)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
print(np.tile(np.arange(5), (5, 1)))


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [5]:
matrix = np.random.rand(10, 10)
# среднее по каждой строке
row_means = matrix.mean(axis=1)
# вычитание среднего
matrix -= row_means.reshape((-1, 1))
print(matrix)

[[-0.0873112  -0.40068603  0.2019376   0.06232055  0.33046547  0.15677803
  -0.40507253 -0.33641535  0.26867618  0.20930728]
 [ 0.06095216 -0.38492427  0.10885014  0.21837985  0.31862687 -0.36650846
   0.2978971  -0.45345493  0.0279761   0.17220544]
 [-0.27053844 -0.23916371  0.5071954  -0.17354665  0.04378933  0.36321509
  -0.13218745  0.05824628  0.0615047  -0.21851455]
 [ 0.28879199  0.10693402  0.03779072 -0.28703155  0.07539053  0.31838023
  -0.50106803  0.00199084  0.26964814 -0.3108269 ]
 [ 0.21403434  0.22165146  0.04223692 -0.31222939 -0.19931463 -0.18314327
   0.24227567 -0.32351686 -0.04704722  0.34505299]
 [-0.33650769 -0.05901239 -0.20025799 -0.24711706  0.09036066  0.46747984
  -0.04172312 -0.31453211  0.19117964  0.45013021]
 [ 0.42809366  0.13306326 -0.11968154 -0.39470663  0.32859229 -0.06631613
  -0.17516825 -0.32405861 -0.19169588  0.38187783]
 [ 0.00470505  0.00788848 -0.21227489  0.39896481 -0.48380997  0.10313958
   0.40204084  0.36225975 -0.28103318 -0.30188046]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
matrix = np.random.rand(10, 10)

# медиана по столбцам
medians = np.median(matrix, axis=0)
print(matrix - medians)



[[-0.0743048   0.38766244 -0.33523075 -0.2197216  -0.47564221 -0.03567871
   0.07696077  0.45269902  0.16741606  0.39526795]
 [ 0.12538494  0.0860054   0.18509132 -0.19700644 -0.11079976  0.50206436
  -0.54503942  0.53814889 -0.41396649  0.5251102 ]
 [-0.03992556 -0.1821867   0.0944693   0.34163225  0.26899673  0.03567871
  -0.40874114  0.73774584  0.06259461 -0.43539451]
 [-0.52241341  0.40480477  0.11109049  0.5309315  -0.15395921 -0.04599648
   0.10014395 -0.0408266   0.05164934  0.13997376]
 [ 0.09549508 -0.17908047 -0.0869739   0.11419898 -0.07628233  0.04348362
   0.23632543  0.69215993 -0.36818558 -0.02717828]
 [ 0.10190218  0.28936741 -0.31746805 -0.01244158  0.14550716 -0.18081237
  -0.26610516 -0.24031197  0.20342743  0.02717828]
 [ 0.21205342 -0.41505349 -0.20923141  0.50941837  0.18617111 -0.13282469
   0.17158806 -0.18041896  0.11769964 -0.30244399]
 [-0.43326841  0.24988441 -0.28831823  0.01244158  0.07628233  0.47683356
   0.18938842  0.0408266  -0.05164934  0.43722457]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
matrix = np.random.rand(5, 5)

max_values = np.max(matrix, axis=1)
min_values = np.min(matrix, axis=1)

max_column = np.expand_dims(max_values, axis=1)
min_column = np.expand_dims(min_values, axis=1)

#соединение по столбцам
result_matrix = np.hstack((matrix, max_column, min_column))

print(result_matrix)

[[0.61963794 0.83401538 0.49717675 0.48575824 0.91730181 0.91730181
  0.48575824]
 [0.44909404 0.30295082 0.17934103 0.14835379 0.80122422 0.80122422
  0.14835379]
 [0.21730894 0.42485177 0.74157332 0.74908545 0.2668228  0.74908545
  0.21730894]
 [0.93654341 0.29063278 0.66334617 0.1966524  0.76130841 0.93654341
  0.1966524 ]
 [0.15006146 0.77975739 0.48677839 0.96950274 0.98912052 0.98912052
  0.15006146]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [18]:

vector = np.arange(1, 52)

# нечетные числа
nechet_vector = vector[vector % 2 == 1]
#удаляем последнее значение, чтобы получить матрицы одинакового размера
nechet_vector = np.delete(nechet_vector, -1)

# четные числа
chet_vector = vector[vector % 2 == 0]


nechet_matrix = nechet_vector.reshape(5, 5)
chet_matrix = chet_vector.reshape(5, 5)


# произведение матриц
proizv_matrix = np.matmul(nechet_matrix, chet_matrix)

# обратная матрица
#reverse_matrix = np.linalg.inv(proizv_matrix)

# определитель матрицы
det_m = np.linalg.det(proizv_matrix)

print("Исходные векторы:")
print("Вектор нечетных чисел:", nechet_vector)
print("Вектор четных чисел:", chet_vector)
print("Матрица нечетных чисел:")
print(nechet_matrix)
print("Матрица четных чисел:")
print(chet_matrix)
print("Произведение матриц:")
print(proizv_matrix)
print("Определитель матрицы:")
#print(reverse_matrix)
print(det_m)

Исходные векторы:
Вектор нечетных чисел: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
Вектор четных чисел: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
Матрица нечетных чисел:
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
Матрица четных чисел:
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
Произведение матриц:
[[ 750  800  850  900  950]
 [1850 2000 2150 2300 2450]
 [2950 3200 3450 3700 3950]
 [4050 4400 4750 5100 5450]
 [5150 5600 6050 6500 6950]]
Определитель матрицы:
0.0


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
tile = np.array([[0, 1], [1, 0]])
matrix = np.tile(tile, (4, 4))
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
